version: "3"

services:
  client-ipfs:
    build: ./client
    ports:
    - "3000:3000"
    volumes:
    - ./client/:/home/node/app
    - /home/node/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true" # use polling to watch for file changes
    networks:
      - sendfiles

  server-ipfs:
    build: ./server # directory of the Dockerfile
    ports:
    - "3200:3200"
    volumes:
      - ./server/:/home/node/app
      - /home/node/app/node_modules
    links:
      - mongodb
    environment:
      CHOKIDAR_USEPOLLING: "true"
    networks:
      - sendfiles

  mongodb:
    image: mongo
    container_name: mongo_db_service
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    logging:
      driver: none
    networks:
      - sendfiles

volumes:
  mongodb:
    driver: local

networks:
  sendfiles:
    driver: bridge